var hierarchy =
[
    [ "bspq21_e4.ParkingManagement.Windows.AuthWindowTest", "classbspq21__e4_1_1_parking_management_1_1_windows_1_1_auth_window_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.data.CalculateFee", "classbspq21__e4_1_1_parking_management_1_1server_1_1data_1_1_calculate_fee.html", null ],
    [ "bspq21_e4.ParkingManagement.server.DAO.DBManager", "classbspq21__e4_1_1_parking_management_1_1server_1_1_d_a_o_1_1_d_b_manager.html", null ],
    [ "bspq21_e4.ParkingManagement.DAO.DBTest", "classbspq21__e4_1_1_parking_management_1_1_d_a_o_1_1_d_b_test.html", null ],
    [ "bspq21_e4.ParkingManagment.Classes.FeeCalculationTest", "classbspq21__e4_1_1_parking_managment_1_1_classes_1_1_fee_calculation_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.data.GuestUser", "classbspq21__e4_1_1_parking_management_1_1server_1_1data_1_1_guest_user.html", null ],
    [ "bspq21_e4.ParkingManagement.server.resource.GuestUserResource", "classbspq21__e4_1_1_parking_management_1_1server_1_1resource_1_1_guest_user_resource.html", null ],
    [ "bspq21_e4.ParkingManagment.Resources.GuestUserResourceTest", "classbspq21__e4_1_1_parking_managment_1_1_resources_1_1_guest_user_resource_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.rsh.GuestUserRSH", "classbspq21__e4_1_1_parking_management_1_1server_1_1rsh_1_1_guest_user_r_s_h.html", null ],
    [ "bspq21_e4.ParkingManagement.RSH.GuestUserRSHTest", "classbspq21__e4_1_1_parking_management_1_1_r_s_h_1_1_guest_user_r_s_h_test.html", null ],
    [ "bspq21_e4.ParkingManagment.Classes.GuestUserTest", "classbspq21__e4_1_1_parking_managment_1_1_classes_1_1_guest_user_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.data.Parking", "classbspq21__e4_1_1_parking_management_1_1server_1_1data_1_1_parking.html", null ],
    [ "bspq21_e4.ParkingManagement.server.resource.ParkingResource", "classbspq21__e4_1_1_parking_management_1_1server_1_1resource_1_1_parking_resource.html", null ],
    [ "bspq21_e4.ParkingManagment.Resources.ParkingResourceTest", "classbspq21__e4_1_1_parking_managment_1_1_resources_1_1_parking_resource_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.rsh.ParkingRSH", "classbspq21__e4_1_1_parking_management_1_1server_1_1rsh_1_1_parking_r_s_h.html", null ],
    [ "bspq21_e4.ParkingManagement.RSH.ParkingRSHTest", "classbspq21__e4_1_1_parking_management_1_1_r_s_h_1_1_parking_r_s_h_test.html", null ],
    [ "bspq21_e4.ParkingManagment.Classes.ParkingTest", "classbspq21__e4_1_1_parking_managment_1_1_classes_1_1_parking_test.html", null ],
    [ "bspq21_e4.ParkingManagement.Windows.PaymentWindowTest", "classbspq21__e4_1_1_parking_management_1_1_windows_1_1_payment_window_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.data.PremiumUser", "classbspq21__e4_1_1_parking_management_1_1server_1_1data_1_1_premium_user.html", null ],
    [ "bspq21_e4.ParkingManagement.server.resource.PremiumUserResource", "classbspq21__e4_1_1_parking_management_1_1server_1_1resource_1_1_premium_user_resource.html", null ],
    [ "bspq21_e4.ParkingManagment.Resources.PremiumUserResourceTest", "classbspq21__e4_1_1_parking_managment_1_1_resources_1_1_premium_user_resource_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.rsh.PremiumUserRSH", "classbspq21__e4_1_1_parking_management_1_1server_1_1rsh_1_1_premium_user_r_s_h.html", null ],
    [ "bspq21_e4.ParkingManagement.RSH.PremiumUserRSHTest", "classbspq21__e4_1_1_parking_management_1_1_r_s_h_1_1_premium_user_r_s_h_test.html", null ],
    [ "bspq21_e4.ParkingManagment.Classes.PremiumUserTest", "classbspq21__e4_1_1_parking_managment_1_1_classes_1_1_premium_user_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.util.PrepareData", "classbspq21__e4_1_1_parking_management_1_1server_1_1util_1_1_prepare_data.html", null ],
    [ "bspq21_e4.ParkingManagment.Util.PrepareDataTest", "classbspq21__e4_1_1_parking_managment_1_1_util_1_1_prepare_data_test.html", null ],
    [ "bspq21_e4.ParkingManagement.Windows.RegisterWindowTest", "classbspq21__e4_1_1_parking_management_1_1_windows_1_1_register_window_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.main.Server", "classbspq21__e4_1_1_parking_management_1_1server_1_1main_1_1_server.html", null ],
    [ "bspq21_e4.ParkingManagement.Server.ServerTest", "classbspq21__e4_1_1_parking_management_1_1_server_1_1_server_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.data.Slot", "classbspq21__e4_1_1_parking_management_1_1server_1_1data_1_1_slot.html", null ],
    [ "bspq21_e4.ParkingManagement.server.data.SlotAvailability", "enumbspq21__e4_1_1_parking_management_1_1server_1_1data_1_1_slot_availability.html", null ],
    [ "bspq21_e4.ParkingManagement.server.resource.SlotResource", "classbspq21__e4_1_1_parking_management_1_1server_1_1resource_1_1_slot_resource.html", null ],
    [ "bspq21_e4.ParkingManagment.Resources.SlotResourceTest", "classbspq21__e4_1_1_parking_managment_1_1_resources_1_1_slot_resource_test.html", null ],
    [ "bspq21_e4.ParkingManagement.server.rsh.SlotRSH", "classbspq21__e4_1_1_parking_management_1_1server_1_1rsh_1_1_slot_r_s_h.html", null ],
    [ "bspq21_e4.ParkingManagement.RSH.SlotRSHTest", "classbspq21__e4_1_1_parking_management_1_1_r_s_h_1_1_slot_r_s_h_test.html", null ],
    [ "bspq21_e4.ParkingManagment.Classes.SlotTest", "classbspq21__e4_1_1_parking_managment_1_1_classes_1_1_slot_test.html", null ],
    [ "bspq21_e4.ParkingManagement.Windows.VentanaParkingTest", "classbspq21__e4_1_1_parking_management_1_1_windows_1_1_ventana_parking_test.html", null ],
    [ "JFrame", null, [
      [ "bspq21_e4.ParkingManagement.client.gui.AuthWindow", "classbspq21__e4_1_1_parking_management_1_1client_1_1gui_1_1_auth_window.html", null ],
      [ "bspq21_e4.ParkingManagement.client.gui.PaymentWindow", "classbspq21__e4_1_1_parking_management_1_1client_1_1gui_1_1_payment_window.html", null ],
      [ "bspq21_e4.ParkingManagement.client.gui.RegisterWindow", "classbspq21__e4_1_1_parking_management_1_1client_1_1gui_1_1_register_window.html", null ],
      [ "bspq21_e4.ParkingManagement.client.gui.VentanaParking", "classbspq21__e4_1_1_parking_management_1_1client_1_1gui_1_1_ventana_parking.html", null ]
    ] ]
];