# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify -Pintegration
    - name: Prepare database for integration tests
      run: 
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < src/main/resources/database.sql
          mvn --batch-mode --update-snapshots compile 
          mvn --batch-mode --update-snapshots datanucleus:enhance
          mvn --batch-mode --update-snapshots datanucleus:schema-create
          mvn --batch-mode --update-snapshots exec:java -Pdata
    - name: Build with Maven including integration tests
      run: mvn --batch-mode --update-snapshots verify -Pintegrationcodecov

    - uses: codecov/codecov-action@v1

      with:
          token: ${{secrets.CODECOV_TOKEN}}
      
